############# English navigation ##############

# main menu
[[main]]
name = "GC Cloud One: Aurora"
url = "/"
weight = 1
identifier = "home"

[[main]]
name = "Contact us"
url = "/contact"
weight = 5

[[main]]
name = "Get involved"
url = "/get-involved"
weight = 6

[[breadcrumb]]
name = "GC Cloud One"
url = "https://gccloudone.ca"
weight = 1
