############# English navigation ##############

# main menu
[[main]]
name = "Service infonuagique unifié du GC: Aurore"
url = "/fr"
weight = 1
identifier = "acceuil"

[[main]]
name = "Plate-forme"
url = "/platform"
weight = 5

  [[main]]
  name = "Proposition"
  parent = "Plate-forme"
  url = "/fr/proposition"
  weight = 1

[[main]]
name = "Contactez-nous"
url = "/fr/contact"
weight = 10

[[main]]
name = "Participez"
url = "/fr/impliquez-vous"
weight = 15

[[breadcrumb]]
name = "Service infonuagique unifié du GC"
url = "https://gccloudone.ca"
weight = 1
